apiVersion: v1
kind: Pod
metadata:
  name: comments-depl
  labels:
    name: comments
spec:
  containers:
    - name: comments
      image: zabozlaev/comments:latest
---
apiVersion: v1
kind: Service
metadata:
  name: comments-srv
spec:
  selector:
    app: comments
  ports:
    - protocol: TCP
      port: 4001
      targetPort: 4001
