apiVersion: v1
kind: Pod
metadata:
  name: query-depl
  labels:
    name: query
spec:
  containers:
    - name: query
      image: zabozlaev/query:latest
---
apiVersion: v1
kind: Service
metadata:
  name: query-srv
spec:
  selector:
    app: query
  ports:
    - protocol: TCP
      port: 4002
      targetPort: 4002
